title: Maurício Mutte - Desenvolvedor Front End
email: mauriciomutte.mm@gmail.com
description: >
  Maurício Mutte é um jovem de 18 anos, estudante e desenvolvedor front end. Começou a programar por 
  curiosidade aos seus 14 anos e desde então busca mais conhecimento para criar programas cada vez 
  mais sofisticados. 
baseurl: ""
url: "https://mauriciomutte.github.io"
twitter_username: mauriciomutte
github_username:  mauriciomutte

markdown: kramdown
permalink: /:title/